name: stockmarket
channels:
  - defaults
dependencies:
  - python=3.6
  - requests
  - click
  - pandas
  - pip:
    - tensorflow==1.13.1
    - keras==2.2.4
    - mlflow==1.23.1
    - scikit-learn==0.21
    - boto3==1.9.164
    - pandas_datareader
